// Texte für „Info und Hilfe“ (Muster: letzte Zeile einer Seite öffnet ein Blatt). Geschrieben von Bill nach ASD-STE100
// auf Deutsch: kurze Sätze, aktive Form, eine Aussage pro Satz, dasselbe Wort für dieselbe Sache. Seit 0.5.4 auch Tresor
// (nur Desktop), Bibliothek, Bereit, Deine Linie, Lumi, Werkzeuge und Lumi-Buch (Auftrag 2026-10-05-04). Notfall bleibt ohne.
// 0.5.5: 14 Antworten richtiggestellt (Auftrag 2026-10-05-07), Frage zur neuen App-Version (Auftrag 2026-10-05-06).
export const HILFE = {
  updates: [
    ["Was ist ein Update?", "Ein Update bringt neue Inhalte oder eine neue App-Version. Die App lädt nur, was sich geändert hat. Das spart Zeit und Daten."],
    ["Wie bekomme ich die neue App-Version?", "Tippe auf „Nach neuer Version suchen“. Ist eine neue Version da, tippe auf „Jetzt laden“. Deine Daten bleiben auf dem Gerät."],
    ["Wann lädt die App?", "Die App lädt nur, wenn du online bist. Unter „Wie oft?“ stellst du ein, wie oft sie prüft. „Manuell“ heißt: Die App prüft nur, wenn du „Jetzt prüfen“ tippst."],
    ["Was ist das Update-Abo?", "Das Update-Abo prüft regelmäßig, ob es neue Inhalte gibt. Du kannst es pausieren. Deine Einstellungen bleiben dabei erhalten."],
    ["Was heißt „Nur im WLAN“?", "Die App lädt dann nicht über das Handynetz. Die App lädt auch nicht über einen Handy-Hotspot."],
    ["Was ist das Zeitfenster?", "Im Zeitfenster darf die App laden. Wähle eine Zeit, in der du das Gerät nicht brauchst, zum Beispiel nachts."],
    ["Wie sicher ist ein Update?", "Jedes Paket hat eine Signatur. Die App prüft die Signatur vor dem Laden. Die App prüft auch jede Datei. Erst dann ersetzt die App den alten Stand. Stimmt etwas nicht, behält die App den alten Stand."],
    ["Was zeigt „Was ist neu“?", "Der Reiter „App“ zeigt, was sich an der App geändert hat. Der Reiter „Inhalte“ zeigt, was sich in den Paketen geändert hat. Ein roter Punkt zeigt: Hier gibt es etwas, das du noch nicht gesehen hast."],
    ["Was prüft „Offline-Bereitschaft“?", "Die App prüft, ob alles für die Nutzung ohne Internet am Gerät ist."],
    ["Was tun „Zurücksetzen“ und „Restlos löschen“?", "„Alles zurücksetzen“ löscht alle Daten und lädt die App neu. „Restlos löschen“ löscht alle Daten und die Offline-Kopie. Beide Schritte fragen zweimal nach. Gelöschte Daten kann niemand wiederherstellen, auch wir nicht."],
    ["Woher kommen die Daten?", "Die Pakete kommen von unserem Server. Die App sendet nur die Versionen deiner Pakete. Bei Pro sendet sie auch deinen Lizenzschlüssel. Die App sendet keine Inhalte und keine Notizen."],
  ],
  tresor: [
    ["Was ist der Tresor?", "Der Tresor ist ein verschlüsselter Bereich auf diesem Gerät. Hier liegen Notizen, Fotos und Dateien, die niemand sonst sehen soll. Den Tresor gibt es nur in der Desktop-App."],
    ["Wie sicher ist der Tresor?", "Die App verschlüsselt jeden Eintrag mit XChaCha20-Poly1305. Den Schlüssel schützt dein Passwort mit Argon2id. Ohne Passwort oder Wiederherstellungscode kann niemand den Inhalt lesen, auch wir nicht."],
    ["Was ist die Notfallmappe?", "Die Notfallmappe ist eine Vorlage mit zehn Abschnitten: Personen, Nummern, Treffpunkte, Dokumente, Versicherungen, Geld, Zugänge, Haus, Tiere und Radio. Trag nur ein, was du im Notfall brauchst. Trag keine vollständigen Kartennummern ein."],
    ["Was ist der Wiederherstellungscode?", "Der Code hat sechs Gruppen zu je fünf Zeichen. Die App zeigt ihn nur einmal. Schreib ihn auf Papier und leg ihn an einen sicheren Ort. Mit dem Code öffnest du den Tresor, wenn du das Passwort vergisst."],
    ["Was passiert, wenn ich das Passwort vergesse?", "Öffne den Tresor mit dem Wiederherstellungscode. Setz danach ein neues Passwort. Wenn du Passwort und Code verlierst, kann niemand den Inhalt wiederherstellen."],
    ["Wann sperrt der Tresor?", "Der Tresor sperrt nach einer Zeit ohne Eingabe. Du wählst 1, 5 oder 15 Minuten. Er sperrt auch, wenn du die App minimierst oder beendest. Du kannst ihn jederzeit selbst sperren."],
    ["Wie sichere ich den Tresor?", "Öffne die Einstellungen des Tresors und tippe auf „Sicherung auf Stick oder Ordner …“. Die App kopiert den verschlüsselten Tresor. Zum Zurückspielen sperrst du den Tresor und tippst auf „Sicherung zurückspielen“. Die Sicherung ersetzt dann den Tresor. Danach gilt das Passwort der Sicherung."],
    ["Verlässt etwas das Gerät?", "Nein. Der Tresor hat keine Verbindung zum Internet."],
  ],
  bibliothek: [
    ["Was zeigt die Bibliothek?", "Die Bibliothek zeigt alle Pakete: Inhalte, Karten, Bücher, Module und mehr. Bei jedem Paket stehen Größe und Version. „Installiert“ heißt: Das Paket liegt auf diesem Gerät und geht ohne Internet."],
    ["Was passiert beim Installieren?", "Die App lädt das Paket und prüft jede Datei. Erst dann ersetzt sie den alten Stand. In der Desktop-App macht ein abgebrochener Download beim nächsten Mal dort weiter. Im Browser beginnt er von vorn."],
    ["Was ist die Signatur?", "Wir signieren jeden Katalog und jedes Paket. Die App prüft die Signatur vor dem Installieren. Stimmt die Signatur nicht, installiert die App nichts."],
    ["Wo liegen die Pakete?", "In der Desktop-App liegen die Pakete im Datenordner der App. Du kannst einen anderen Ordner wählen, zum Beispiel eine externe Platte. Im Browser liegen die Pakete im Speicher des Browsers."],
    ["Was tut „Entfernen“?", "„Entfernen“ löscht das Paket von diesem Gerät. Deine Notizen und dein Tresor bleiben. Du kannst das Paket später wieder installieren."],
    ["Was ist ein Modul?", "Ein Modul ist ein Paket mit eigener Oberfläche, zum Beispiel ein Spiel. Ein Modul läuft abgeschlossen. Es hat keinen Zugang zum Internet und keinen Zugang zu deinem Tresor. Es speichert höchstens 1 MB eigene Daten."],
    ["Warum kann ich ein Paket nicht laden?", "Manche Pakete brauchen eine neuere App. Dann steht dort „Braucht App“ und die Versionsnummer. Aktualisiere zuerst die App. Manche Pakete gehen nur in der Desktop-App oder nur mit Pro."],
    ["Kann ich Pakete ohne Internet einspielen?", "Ja, in der Desktop-App. Tippe auf „Datenträger durchsuchen“ und dann bei einem Fund auf „Einspielen“. Oder tippe auf „Ordner wählen …“, dann spielt die App sofort ein. Die App prüft die Signatur auch hier."],
  ],
  bereit: [
    ["Was zeigt die Bereit-Zahl?", "Die Zahl zeigt, wie gut du auf einen Notfall vorbereitet bist. Sie geht von 0 bis 100. Unter 30 heißt „Anfang“, unter 60 „unterwegs“, unter 80 „gut“. Ab 80 heißt „bereit“."],
    ["Woraus entsteht die Zahl?", "Die Zahl hat vier Teile: Inhalte (20), Dinge (35), Menschen (25) und Können (20). Jeder Punkt in der Liste zählt zu einem Teil."],
    ["Warum sinkt die Zahl?", "Vorräte und Absprachen verfallen. Jeder Punkt hat eine Frist, zum Beispiel 12 Monate für Wasser und 6 Monate für Powerbanks. Nach der Frist sinkt der Punkt in drei Monaten auf null."],
    ["Was heißt „Bestätigen“?", "„Bestätigen“ heißt: Ich habe das heute geprüft. Die App speichert das Datum. Die Frist beginnt neu."],
    ["Was zählt die App von selbst?", "Österreich-Paket, Wissen, Karte und Notfallmappe zählt die App von selbst. Alles andere bestätigst du."],
    ["Warum steht „verdächtig gut“ da?", "Über 95 fragt die App nach deinem letzten Probeabend, wenn du in den letzten drei Monaten keinen bestätigt hast. Ein Probeabend ist ein Abend ohne Strom. Er zeigt, was wirklich fehlt."],
    ["Wer sieht meine Zahl?", "Nur du. Die Zahl bleibt auf diesem Gerät."],
  ],
  "pause-linie": [
    ["Was ist „Deine Linie“?", "„Deine Linie“ zeigt, wie Pause dich kennt: was du magst, wie schwer es sein soll und was diese Woche war."],
    ["Wie wählt Pause einen Happen?", "In den ersten drei Wochen lernt Pause dich kennen und wählt, was du am wenigsten gespielt hast. Danach wählt Pause meist etwas Vertrautes, manchmal etwas Ähnliches und selten etwas Neues. Morgen-Happen kommen bis 12 Uhr. Abend-Happen kommen ab 18 Uhr. Dieselbe Form kommt nicht zweimal hintereinander, wenn eine andere passt."],
    ["Was tun „Mehr davon“, „Passt“ und „Nicht mehr“?", "„Mehr davon“ bringt diese Form öfter. „Passt“ ändert nichts. „Nicht mehr“ nimmt die Form heraus. Du kannst sie unter „Nicht mehr“ zurückholen."],
    ["Wie oft kommt ein Happen?", "Das bestimmt dein Appetit: wenig, mittel oder viel. Öffnest du die App innerhalb von 10 Minuten wieder, kommt kein neuer Happen. Im Notfall-Bereich kommt nie ein Happen."],
    ["Wie stellt Pause die Schwierigkeit ein?", "Pause schaut auf deine Treffer. Bei sehr vielen Treffern wird es schwerer. Bei wenigen Treffern wird es leichter. Du kannst die Stufe auch selbst ändern."],
    ["Was ist der Rückspiegel?", "Höchstens einmal im Monat zeigt Pause einen Rückspiegel. Er nennt, was du dazugelernt hast, oder was du am liebsten gespielt hast. Gibt es beides nicht, kommt kein Rückspiegel. Pause zählt dabei keine Tage und keine Besuche."],
    ["Was sagt Pause über die Wirkung?", "Pause ist zuerst Unterhaltung. Pause verspricht keine Wirkung auf Gedächtnis oder Gesundheit. Wenn du dich sorgst, sprich mit deiner Ärztin oder deinem Arzt."],
    ["Wo liegen meine Daten?", "Alles bleibt auf diesem Gerät. „Linie zurücksetzen“ und „Spiel-Log löschen“ löschen deine Daten."],
  ],
  lumi: [
    ["Was ist die Lumi?", "Die Lumi ist eine Begleiterin aus einer Höhle unter dem Eis. Sie gibt dir Tipps. Sie ist eine erfundene Figur."],
    ["Welche Arten gibt es?", "Es gibt drei Arten. „Aus mit Textkarten“ zeigt Tipps als Karte. „Lumi mit Tipps“ zeigt die Lumi mit Tipps. „Tipps aus“ zeigt nur die Bereit-Zahl."],
    ["Wann sagt die Lumi „ich“?", "Die Lumi sagt nur „ich“, wenn sie einen Namen hat und du „Lumi mit Tipps“ gewählt hast. Ohne Namen zeigt die App keine Sätze mit „ich“."],
    ["Wie oft kommt ein Tipp?", "Bei „Lumi mit Tipps“ wählst du normal, seltener oder aus. Liest du die Tipps, kommen sie etwas öfter. Wischst du sie weg, kommen sie seltener. Pro Sitzung kommen höchstens 12 Tipps."],
    ["Was tun „Mehr davon“, „Passt“ und „Nicht mehr“?", "„Mehr davon“ bringt diese Sorte öfter. „Passt“ ändert nichts. „Nicht mehr“ bringt diese Sorte seltener, und dieser Satz kommt nicht wieder. Keine Sorte verschwindet ganz. Unter „Was Lumi gelernt hat“ siehst und änderst du das."],
    ["Wann schläft die Lumi?", "Die Lumi mit Figur schläft zuerst von 22 bis 6 Uhr. Danach lernt sie deine Schlafenszeit. Tippst du sie an, wacht sie für eine Minute auf."],
    ["Was macht „Merken“?", "„Merken“ legt einen Satz in das Heft „Was Lumi gesagt hat“. Gemerkte Sätze bleiben. Du kannst jeden Satz einzeln löschen."],
    ["Was tut die Lumi nie?", "Die Lumi schickt keine Nachrichten. Sie bettelt nicht. Sie stirbt nicht. Im Notfall-Bereich schweigt sie."],
    ["Wo liegen die Daten der Lumi?", "Alles bleibt auf diesem Gerät."],
  ],
  werkzeuge: [
    ["Was sind die Werkzeuge?", "Die Werkzeuge sind kleine Helfer ohne Internet: Radio, Sonne und Mond, Einheiten und Vorrat."],
    ["Woher kommen die Radio-Frequenzen?", "Du trägst die Frequenzen für dein Bundesland selbst ein. Die App speichert sie auf diesem Gerät. Im Stromausfall hörst du die Lage im Radio, mit Batterie oder Kurbel."],
    ["Wie rechnet „Sonne und Mond“?", "Die App rechnet ohne Internet. Sie nimmt die Landeshauptstadt deines Bundeslandes. Sie nimmt nicht deinen Standort. Die Zeiten stimmen auf etwa zwei Minuten."],
    ["Was rechnet der Vorrat?", "Der Vorrat rechnet Wasser und Essen für deinen Haushalt. Er nimmt 2 Liter Wasser pro Person und Tag. Er speichert nichts."],
    ["Was rechnen die Einheiten?", "Länge, Gewicht, Volumen, Fläche und Temperatur. Dazu kommen Kochmaße."],
  ],
  "lumi-buch": [
    ["Was ist das Lumi-Buch?", "Das Lumi-Buch erzählt, wie die Lumis gelernt haben, gut zusammenzuleben. Es ist eine erfundene Geschichte."],
    ["Wie wird ein Stück lesbar?", "Unter einem Satz deiner Lumi steht „Aus dem Lumi-Buch“. Tippe darauf. Dann ist dieses Stück im Buch lesbar."],
    ["Warum gibt es Lücken?", "Manche Stücke hat dir deine Lumi noch nicht erzählt. Manche Stücke kommen erst mit einer neuen Funktion der App. Beide Arten von Lücken siehst du im Buch."],
    ["Was zeigt die Prozentzahl?", "Die Zahl zeigt, wie viel vom Buch du lesen kannst. 100 % gibt es erst, wenn alle Stücke lesbar sind."],
    ["Was ist das Schlussstück?", "Das letzte Stück öffnet sich, wenn du den Rest des letzten Kapitels gelesen hast."],
    ["Wie öffne ich das Buch?", "In der Bibliothek tippst du beim Lumi-Buch auf „Lesen“. Ist die Lumi mit Figur eingeschaltet, steht das Buch auch in der Übersicht. Den Link „Aus dem Lumi-Buch“ unter einem Satz gibt es nur, wenn deine Lumi einen Namen hat."],
  ],
};
